"""Add passkey support with explicit constraint

Revision ID: 8ff2fd88b6a2
Revises: d0e870e14718
Create Date: 2024-12-01 22:58:35.281339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff2fd88b6a2'
down_revision = 'd0e870e14718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passkey_credential_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('passkey_public_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('passkey_sign_count', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_user_passkey_credential_id', ['passkey_credential_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_passkey_credential_id', type_='unique')
        batch_op.drop_column('passkey_sign_count')
        batch_op.drop_column('passkey_public_key')
        batch_op.drop_column('passkey_credential_id')

    # ### end Alembic commands ###
